# This plugin was made by vitor1227_OP
# Make sure Vault is installed on your server, this plugin uses Vault as the basis for money management.

# Variables that can be used:

# {item_quantity} - Quantity of items sold.
# {total_value} - Total value of items sold.

items:
  DIAMOND: 100.0
  GOLD_INGOT: 50.0
  IRON_INGOT: 20.0

messages:
  sell_all: "§b§o[SellAll] §aVocê vendeu §f§o{item_quantity} §aitens por §2§o${total_value}§a!"
  sell_shift: "§b§o[ShiftSell] §aVocê vendeu §f§o{item_quantity} §aitens por §2$§o{total_value}§a!"
  cooldown_message: "§b§o[ShiftSell] §cAguarde {time_left} segundos antes de vender novamente."
sell:
  interval: 5 # Time in seconds

bonus:
  infinity:
    sell_bonus: 1.30 # 30% bonus
    sell_message: '§f[VIP Infinity] §a+ 30% bônus, totalizando §2§o${value_with_bonus}§a!'
  diamond:
    sell_bonus: 1.20 # 20% bonus
    sell_message: '§9[VIP Diamante] §a+ 20% bônus, totalizando §2§o${value_with_bonus}§a!'
  gold:
    sell_bonus: 1.10 # 10% bonus
    sell_message: '§6[VIP Ouro] §a+ 10% bônus, totalizando §2§o${value_with_bonus}§a!'
  emerald:
    sell_bonus: 1.05 # 5% bonus
    sell_message: '§a[VIP Esmeralda] §a+ 5% bônus, totalizando §2§o${value_with_bonus}§a!'
  default:
    sell_bonus: 1.0 # 0% bonus
    sell_message: '§7[Membro] + 0% bônus, você não possui VIP!'